<a href="https://colab.research.google.com/github/Ranniellsaur/Linear-algebra-58020/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from numpy.linalg import eig

A = np.array([[-12,3],[4,1]])
print(A)

inv_A = np.linalg.inv(A)

B = np.array([[0],[0]])
print(B)

X = np.linalg.solve(A, B)
print(X)

X = np.dot(inv_A, B)

[[-12   3]
 [  4   1]]
[[0]
 [0]]
[[-0.]
 [ 0.]]


In [6]:
A = np.array([[-6,3],[4,5]])
print('Vector A:\n', A)

w, v = eig(A)
print('Eigenvalues:\n', w)
print('Eigenvectors:\n', v)



# Example 2

A = np.array([[2,2,4],[1,3,5],[2,3,4]])
print(A)
s,t = np.linalg.eig(A)
print(s.round())
print(t.round())
c=np.dot(A,t.round())
print(c)

Vector A:
 [[-6  3]
 [ 4  5]]
Eigenvalues:
 [-7.  6.]
Eigenvectors:
 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]
[[2 2 4]
 [1 3 5]
 [2 3 4]]
[ 9.  1. -1.]
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]
[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
