<a href="https://colab.research.google.com/github/Ranniellsaur/Linear-algebra-58020/blob/main/Linear_Transformation_demo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

A = np.array([[4, 10, 8], [10, 26, 26], [8, 26, 61]])
print(A)
B = np.array([[44], [128], [214]])
print(B)
#AA^-1X = BA^-1

## Solving for the inverse of A
A_inv = np.linalg.inv(A)
print(A_inv)

## Solving for BA^-1
X = np.dot(A_inv, B)
print(X)


[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
[[ 44]
 [128]
 [214]]
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]
[[-8.]
 [ 6.]
 [ 2.]]
