<a href="https://colab.research.google.com/github/Ranniellsaur/Linear-algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python program to inverse

## Python program to inverse a 3x3 matrix 

In [28]:
import numpy as np # import numpy module to use its functions

# inverse
A = np.array([[1,2,3],# create 3x3 array
              [4,9,6],
              [7,8,9]]) 
inverse_of_A = np.linalg.inv(A) # inverse the given 3x3 matrix then assign it to another variable
print("The inverse array is ")
print(inverse_of_A) # display the inversed matrix
print()

# transpose
transpose_of_A = np.dot(A, inverse_of_A) # use dot() func to get transpose of the given 3x3 matrix
print("The transpose array is ")
print(transpose_of_A) # display the transposed matrix





The inverse array is 
[[-0.6875     -0.125       0.3125    ]
 [-0.125       0.25       -0.125     ]
 [ 0.64583333 -0.125      -0.02083333]]

The transpose array is 


## Python program to inverse a 4x4 matrix

In [29]:
B = np.array([[1, 2, 3, 4],  # Create  4x4 array
                [10, 11, 14, 25],
                [20, 8, 7, 55], 
                [40, 41, 42, 43]])

# inverse
inverse_of_B =  np.linalg.inv(B)  # inverse the given 4x4 matrix then assign it to another variable
print("The inverse array is ") 
print(inverse_of_B) # display the inverse matrix
print()

# transpose
transpose_of_B = np.dot(B, inverse_of_B) # use dot() func to get transpose of the given 3x3 matrix
print("The transpose array is ")
print(transpose_of_B) # display the transposed matrix

The inverse array is 
[[-15.07692308   4.9         -0.8         -0.42307692]
 [ 32.48717949 -10.9          1.8          1.01282051]
 [-20.84615385   7.1         -1.2         -0.65384615]
 [  3.41025641  -1.1          0.2          0.08974359]]

The transpose array is 
[[ 1.00000000e+00  0.00000000e+00  3.33066907e-16  2.22044605e-16]
 [ 8.43769499e-15  1.00000000e+00  1.08246745e-15  2.49800181e-16]
 [-4.39648318e-14 -1.99840144e-15  1.00000000e+00  1.94289029e-16]
 [-4.57411886e-14  1.66533454e-14 -2.08166817e-15  1.00000000e+00]]
