<a href="https://colab.research.google.com/github/Ranniellsaur/Linear-algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Midterm Exam

In [16]:
# Create a python code that displays a square matrix whose length is 5

import numpy as np   # import numpy module

square_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]) # 5x5 matrix
print(square_matrix) # display square matrix


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [17]:
# Create a Python code that displays a square matrix whose elements below the principal diagonal are zero

square_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]) # 5x5 matrix
print(np.triu(square_matrix))

[[ 1  2  3  4  5]
 [ 0  7  8  9 10]
 [ 0  0 13 14 15]
 [ 0  0  0 19 20]
 [ 0  0  0  0 25]]


In [14]:
# Create a Python code that displays a square matrix which is symmetrical 
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A.T) # Transpose of matrix A
B = np.matmul(A,A.T)
print(B) # Transpose of matrix A


[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [6]:
# What is the inverse of matrix C? Show your solution by python coding

C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) # initial matrix
Inv_C = np.linalg.inv(C)  # inverse of matrix C
print(Inv_C) # Display  inverse of matrix C

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


In [8]:
# What is the determinant of the given matrix in Question 4? Show your solution by python coding.

C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) # matrix in question 4
print(round(np.linalg.det(C))) # display the rounded result of determinant of the matrix C 


5


In [11]:
#  Find the roots of the linear equations by showing its python codes 

A = np.array([[5,4,1],[10,9,4],[10,13,15]]) 
inv_A = np.linalg.inv(A) # inverse of the given matrix
B = np.array([[3.4],[8.8],[19.2]]) 
C = np.dot(inv_A,B) # dot product
print(C) # display result matrix

[[0.2]
 [0.4]
 [0.8]]
