<a href="https://colab.research.google.com/github/Ranniellsaur/Linear-algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Practical Lab Exam 1

In [22]:
import numpy as np


W = np.array([[1,-3], [2,-2],[3,1]])
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
Y = np.array([[1,2,0],[0,-1,2]])
Z = np.array([[0,1],[2,3]])

# Problem 1

# a. WY
# b. Z+Z
# c. 3X


# Answer in a
print(np.dot(W,Y))

# Answer in b
print(Z + Z)

#Answer in  c
print(3 * Z)
print()


# Problem 2 || Which of the ff. if true?

# a. The product (YW^2) is not defined
# b. WY - X
# c. YW - Z^2


# a. 
print('this is the answer of a')
print(np.dot(Y,W) ** 2)

# b. 
print('this is the answer of b')
print(np.dot(W,Y) - X)


# c.
print('this is the answer of c')
print(np.dot(Y,W) - Z ** 2)


print('The right answer is b.')











[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]
[[0 2]
 [4 6]]
[[0 3]
 [6 9]]

this is the answer of a
[[25 49]
 [16 16]]
this is the answer of b
[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]
this is the answer of c
[[ 5 -8]
 [ 0 -5]]
