<a href="https://colab.research.google.com/github/Ranniellsaur/Linear-algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prelim Exam

## Question 1 : 4 x 4 matrix whose diagonal elements are all one (1's).

In [4]:
import numpy as np
# Create 4 x 4 matrix whose diagonal elements are all one (1's).

# 1st solution
C = np.diagonal([[1,2,3,4],[2,1,3,4],[3,2,1,4],[4,3,2,1]])
print(C) # this will only print all the diagonal elements which has a value of 1

# 2nd solution
C = np.zeros((4,4))
np.fill_diagonal(C,1)
print(c) # this will print the entire 4x4 matrix 



[1 1 1 1]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Question 2 :  show a solution that doubles all the values of each element

In [5]:
# Double all the values of the elements in Question 1

print(C * 2)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


## Question 3 : cross-product of matrices, A = [2,7,4] and B = [3,9,8]


In [6]:
A = [2,7,4]
B = [3,9,8]

# cross product
answer = np.cross(A,B)
print(answer)

[20 -4 -3]
