<a href="https://colab.research.google.com/github/Ranniellsaur/Linear-algebra-58020/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear Transformation

In [5]:
import numpy as np

A = np.array([[1, 1, 1], [1, 2, 2], [1, 2 ,3 ]])
print(A)

B = np.array([[5], [6], [8]])
print(B)


#AA^-1X = BA^-1
## Solving for the inverse of A
A_inv = np.linalg.inv(A)
print(A_inv)

## Solving for BA^-1
X = np.dot(A_inv, B)
print(X)


[[1 1 1]
 [1 2 2]
 [1 2 3]]
[[5]
 [6]
 [8]]
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]
[[ 4.]
 [-1.]
 [ 2.]]
