<a href="https://colab.research.google.com/github/Ranniellsaur/Linear-algebra-58020/blob/main/Vector_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operations

In [4]:
import numpy as np


#create a 1x3 array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
#Create a 2 x 3 matrix
b = np.array([[1,2,3],[4,5,6]]) # This is an example of rectangular matrix
print(b)


[[1 2 3]
 [4 5 6]]


In [8]:
#Create 3 x 3 matrix
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#Create a constant array with all values are  6
d = np.full((4,4), 6) # This is an example of square matrix
print(d)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [10]:
#Create a diagonal matrix
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)

[1 5 9]


In [11]:
#Create a identity matrix
f = np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
#Create a zero matrix
g = np.zeros((4,5))
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
#Create a empty matrix
h = np.empty((0,5))
print(h)

[]


In [15]:
#Addition of matrix
i = np.array([[1,2,3],[4,5,6]])
j = np.zeros((2,3))
print(i + j)

[[1. 2. 3.]
 [4. 5. 6.]]
